---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ${INSOLAR_NAMESPACE}
bases:
  - https://github.com/insolar/gitops/rsyslog
patchesStrategicMerge:
  - patch-imagepullsecret.yaml
  - patch-pvc.yaml
resources:
  - resource-pvc.yaml
