---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rsyslog
spec:
  template:
    spec:
      containers:
        - name: rsyslog
          volumeMounts:
          - name: rsyslog-data
            mountPath: /logs
      volumes:
        - name: rsyslog-data
          persistentVolumeClaim:
            claimName: rsyslog-data
